services:
  db:
    image: postgres:16
    container_name: recsys-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: recsys
      POSTGRES_USER: recsys_user
      POSTGRES_PASSWORD: recsys_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
