services:
  db:
    image: postgres:16
    container_name: recsys-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: recsys
      POSTGRES_USER: recsys_user
      POSTGRES_PASSWORD: recsys_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./recsys-backend/internal/storage/createDB.sql:/docker-entrypoint-initdb.d/001_create_schema.sql:ro

  api:
    build:
      context: ./recsys-backend
      dockerfile: Dockerfile
    container_name: recsys-api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./recsys-backend/.env
    environment:
      # переопределение значений из .env для запуска внутри compose
      APP_ADDR: ":8080"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "recsys"
      DB_USER: "recsys_user"
      DB_PASSWORD: "recsys_pass"
    ports:
      - "8080:8080"

volumes:
  pgdata:
